name: Build APK Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dorg.gradle.parallel=false
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK 34
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          target: default

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android build
        uses: actions/cache@v3
        with:
          path: |
            app/build
          key: ${{ runner.os }}-android-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-build-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean build
        run: ./gradlew clean --no-daemon

      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon --max-workers=2

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-${{ github.run_number }}
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/mapping/release/

      - name: Upload build logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            app/build/reports/
            build/reports/
            **/build.log
